#! /bin/sh
### BEGIN INIT INFO
# Provides:             gowebserver
# Required-Start:       $local_fs $remote_fs
# Required-Stop:        $local_fs $remote_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    gowebserver
# Description:          gowebserver
### END INIT INFO


. /lib/lsb/init-functions
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/gowebserver
NAME=gowebserver
DESC=gowebserver

RUNDIR=/var/run
PIDFILE=$RUNDIR/gowebserver.pid

test -x $DAEMON || exit 0

case "$1" in
  start)
        mkdir -p $RUNDIR
        touch $PIDFILE

        if start-stop-daemon --start --oknodo --quiet --make-pidfile --pidfile $PIDFILE --background --exec $DAEMON
        then
                echo "=======>>>>> GOWEBSERVER started successfully. - $NAME"
        else
                echo "=======>>>>> GOWEBSERVER failed to start - $NAME"
        fi
        ;;
  stop)
        echo -n "Stopping $DESC: "
        if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
        then
                echo "=======>>>>> Stopped $NAME."
        else
                echo "=======>>>>> Unable to stop $NAME"
        fi
        rm -f $PIDFILE
        sleep 1
        ;;

  restart|force-reload)
        ${0} stop
        ${0} start
        ;;

  *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
